from typing import Literal

WorkoutClass = Literal["Light", "Moderate", "Hard"]
Intensity = Literal["low", "medium", "high"]


def classify_workout(duration: int, intensity: Intensity) -> WorkoutClass:
    if duration > 60 or intensity == "high":
        return "Hard"
    if 30 <= duration <= 60 and intensity == "medium":
        return "Moderate"
    return "Light"


def get_food_counts(workout_class: WorkoutClass) -> dict[str, int]:
    if workout_class == "Hard":
        return {"carbs": 5, "protein": 4, "antioxidants": 4}
    if workout_class == "Moderate":
        return {"carbs": 4, "protein": 3, "antioxidants": 3}
    return {"carbs": 3, "protein": 2, "antioxidants": 2}


# Future LLM integration point.
# Keep this stub to preserve architecture compatibility while the app
# currently uses deterministic rule-based recommendations.
#
# def get_llm_recommendations(duration: int, intensity: Intensity) -> dict[str, list[str]]:
#     """Return food recommendations generated by an LLM provider."""
#     raise NotImplementedError("LLM recommendations are not implemented yet.")
