from typing import Literal

WorkoutClass = Literal["Light", "Moderate", "Hard"]
Intensity = Literal["very_low", "low", "moderate", "moderate_high", "high", "very_high"]

INTENSITY_SCORES: dict[str, int] = {
    "very_low": 1,
    "low": 2,
    "moderate": 3,
    "moderate_high": 4,
    "high": 5,
    "very_high": 6,
}


def classify_workout(
    duration: int,
    mileage: float,
    pace: float,
    intensity: Intensity,
    perceived_effort: int,
) -> tuple[WorkoutClass, int]:
    score = 0

    # Duration contribution (1-3)
    if duration < 30:
        score += 1
    elif duration <= 60:
        score += 2
    else:
        score += 3

    # Mileage contribution (1-3)
    if mileage < 5:
        score += 1
    elif mileage <= 10:
        score += 2
    else:
        score += 3

    # Intensity contribution (1-6)
    score += INTENSITY_SCORES[intensity]

    # Perceived effort contribution (1-3)
    if perceived_effort <= 1:
        score += 1
    elif perceived_effort <= 3:
        score += 2
    else:
        score += 3

    if score <= 6:
        return "Light", score
    elif score <= 11:
        return "Moderate", score
    else:
        return "Hard", score


def get_food_counts(workout_class: WorkoutClass) -> dict[str, int]:
    if workout_class == "Hard":
        return {"carbs": 4, "protein": 4, "antioxidants": 3, "fats": 2}
    if workout_class == "Moderate":
        return {"carbs": 3, "protein": 3, "antioxidants": 2, "fats": 2}
    return {"carbs": 2, "protein": 2, "antioxidants": 2, "fats": 1}


def get_macro_allocation(workout_class: WorkoutClass) -> dict[str, int]:
    if workout_class == "Hard":
        return {"carbs_percent": 60, "protein_percent": 25, "fat_percent": 15}
    if workout_class == "Moderate":
        return {"carbs_percent": 55, "protein_percent": 25, "fat_percent": 20}
    return {"carbs_percent": 45, "protein_percent": 25, "fat_percent": 30}


def get_meal_plan_counts(workout_class: WorkoutClass) -> list[dict]:
    """Return per-meal food counts per category."""
    if workout_class == "Hard":
        return [
            {"meal_name": "Breakfast", "carbs": 2, "protein": 1, "antioxidants": 0, "fats": 1},
            {"meal_name": "Lunch",     "carbs": 2, "protein": 2, "antioxidants": 1, "fats": 1},
            {"meal_name": "Dinner",    "carbs": 1, "protein": 2, "antioxidants": 2, "fats": 1},
        ]
    if workout_class == "Moderate":
        return [
            {"meal_name": "Breakfast", "carbs": 2, "protein": 1, "antioxidants": 0, "fats": 1},
            {"meal_name": "Lunch",     "carbs": 1, "protein": 1, "antioxidants": 1, "fats": 1},
            {"meal_name": "Dinner",    "carbs": 1, "protein": 1, "antioxidants": 2, "fats": 1},
        ]
    return [
        {"meal_name": "Breakfast", "carbs": 1, "protein": 1, "antioxidants": 0, "fats": 1},
        {"meal_name": "Lunch",     "carbs": 1, "protein": 1, "antioxidants": 1, "fats": 0},
        {"meal_name": "Dinner",    "carbs": 0, "protein": 1, "antioxidants": 2, "fats": 1},
    ]


# Future LLM integration point.
# Keep this stub to preserve architecture compatibility while the app
# currently uses deterministic rule-based recommendations.
#
# def get_llm_recommendations(
#     duration: int, mileage: float, pace: float,
#     intensity: Intensity, perceived_effort: int,
# ) -> dict[str, list[str]]:
#     """Return food recommendations generated by an LLM provider."""
#     raise NotImplementedError("LLM recommendations are not implemented yet.")
